#FROM nginx:alpine

# Copy the static HTML content into the Nginx default web directory
# The website content is in the parent directory relative to the Dockerfile
#COPY Dev /usr/share/nginx/html

# Expose port 80, the default HTTP port Nginx listens on
#EXPOSE 80
# The default command of the Nginx image starts the web server
# No need to specify CMD here unless you want to override it
#
# Use a pinned version of nginx based on Alpine for stability
FROM nginx@sha256:87a5dfd8fb35421c9692272ffcc940a799a3c56de1d9cb151f8755fc8850bb8d

# Copy static site files into nginx's default content directory
COPY ./site-content /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

g